### ISSUE TITLE
[Feature]: Add addon errors

### ISSUE THREAD

**Issue by Laurick** [rothiotome/godot-very-simple-twitch#10]
### Description

VST return no errors so far in some flows like joining a chat or raising the local server to the app

### Current Behavior

If you tries to connect to a empty chat or the IRC server returns an error the app/game doesn't get notify properly

### How

Wa can use the same data object as described in #9 with the same structure for return the errors. The way to return the errors can be a new signal called on_plugin_error (TBD) and notify error through that.

We can change also the name of the other signals to match the godot code style taking advantage of these and being good (girl|boy)scauts o7

**Comment by rothiotome** [comment]
Same as #9, should be prioritized. Working on this (and changing the node names, it's a remnant of my Unity times haha)
