### ISSUE TITLE
[Feature]:  Add credentials to action

### ISSUE THREAD

**Issue by Laurick** [rothiotome/godot-very-simple-twitch#18]
### Description

The github action needs credentials in order to push releases and do some stuff

### Current Behavior

Release version github action fails 

### How

Go to your profile 
Generate a new token with write/read repo scopes
Put it as a secret (GITHUB_ACTION name?) in this repo
Relaunch the action

**Comment by rothiotome** [comment]
Updated secret name in 8c958ad and uploaded github action. We will test in the next release as it's not urgent
