### ISSUE TITLE
Contributing, code of conduct, author files and templates

### ISSUE THREAD

**Issue by Laurick** [rothiotome/godot-very-simple-twitch#2]
# Why
There is no files about the author ( rothio ), coc and contributing stuff and I think is important as a free software. Also that makes super profesional look :)

For template files i think will be nice to get the same as vsc unity edition to keep the docs nice, with all the information and clean like: #1. We can add or remove parts and stuff.

# How
Adding the files:

* Authors
* Issues template
* PR template
* "CoC" Code of counduct
* Contributing

Which can be copied from another rothio's repo after a check.

# Notes
Maybe this must be some separated issues but I decided to group them. And for some reason I cant put labels on this so read this like a discussion

**Comment by rothiotome** [comment]
I think your PR was super clear to understand, we should totally add that information in order to make it easier for future contributors. Do you have the template and the files you commented? Do you want to add them to the project?
