### ISSUE TITLE
[Bug]: Falla en Guardar Client ID 

### ISSUE THREAD

**Issue by METROINDIO7** [rothiotome/godot-very-simple-twitch#22]
### Project Version

0.0.1

### What is the issue?

Muestro video para que se entienda mejor cada vez que coloco la ID no se guarda si reinicias el proyecto se borra y no entiendo porque

https://github.com/user-attachments/assets/a799518f-2111-4de8-ab00-572ab2f6be14

### Steps to reproduce

1. copiar ID
2. pegarla
3. Reiniciar proyecto

### Current behavior

se Borra la ID

### Expected behavior

Que se guarde la ID

**Comment by rothiotome** [comment]
Resuelto en #25. Puedes actualizar desde el repositorio o esperar a la siguiente release :)
