### ISSUE TITLE
Add github action

### ISSUE THREAD

**Issue by Laurick** [rothiotome/godot-very-simple-twitch#4]
# Why
I think a github action ziping the addon folder and uploading to github relases is a good feature for these reasons:

* It's cool
* Will be usefull for more badges on docs 👀 
* Someone who only wants the addon dont need the examples
* Doesn't affect the asset store on godot.
* It's automatic

# How
My proposal its to make a github action to make a zip with the addon folder only on "v*.*.*" tags so in each tag a version will be realeases with that versioning

**Comment by rothiotome** [comment]
I think it's a great idea, specially because of the opportunity of adding new badges, of course.

Do you have a template we can use? Feel free to do a PR if you have any

**Comment by Laurick** [comment]
Yeah, it's only one file. Will do

**Comment by rothiotome** [comment]
Added access token and merged
